version: '3'
services:
  sap-comparison:
    image: mattocci/cmdstan-verse-zsh:4.3.2
    container_name: sap-comparison
    user: rstudio
    environment:
      - RENV_PATHS_CACHE=/renv
      - INSIDE_CONTAINER=true
      - INSIDE_DOCKER=true
    volumes:
      - $HOME/sap-comparison:/home/rstudio/sap-comparison
      - $HOME/renv:/renv
