---
title: "dummy test"
author: "Masatoshi Katabuchi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
# link-citations: yes
# csl: templates/ecology-letters.csl
# bibliography: templates/seedling.bib
output:
  html_document:
    theme: spacelab #readable #sandstone #spacelab #flatly
    toc: true
    toc-depth: 2
    toc-title: Contents
    self-contained: true
    smooth-scroll: true
    highlight-style: github
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)
```

```{r,include=FALSE}
library(tidyverse)
library(targets)
library(tarchetypes)
library(kableExtra)
library(here)
library(loo)
library(bayesplot)
source(here("R", "stan.R"))
```


# Dummy data

```{r}
tar_load(dummy_data)
dummy <- dummy_data$data

dummy |>
  mutate(species = as.factor(species)) |>
  mutate(pressure = as.factor(pressure)) |>
  ggplot(aes(y = y, x = pressure, col = pressure)) +
  geom_violin() +
  geom_point(position = position_dodge(width = 0.90)) +
  facet_wrap(~ species)
```

## Model without interactions

```{r}
tar_load(fit_dummy_draws_anova)
tar_load(fit_dummy_noint_draws_anova)
```

```{r}
mcmc_intervals(
  fit_dummy_noint_draws_anova,
  pars = c("mu_hat"),
  prob = 0.9,
  prob_outer = 0.95,
  regex_pars = "alpha\\[[1-5]\\]|beta\\[[1-9]\\]|tau\\[[1-9]\\]")
```

## Model with interactions

```{r}
mcmc_intervals(
  fit_dummy_draws_anova,
  pars = c("mu_hat"),
  prob = 0.9,
  prob_outer = 0.95,
  regex_pars = "alpha\\[[1-5]\\]|beta\\[[1-9]\\]|tau\\[[1-9]\\]")
```
