---
title: ""
author: "Masatoshi Katabuchi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
format:
  html:
    theme: coderpro
    toc: true
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
    standalone: true
    embed-resources: true
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)
```

```{r}
renv::install("adletaw/captioner")
renv::repair()
library(targets)
library(tidyverse)
```

```{r}
source(here::here("R/data_clean.R"))
source(here::here("R/stan.R"))
source(here::here("R/figs.R"))
source(here::here("R/tables.R"))
source(here::here("R/scale.R"))
source(here::here("R/traits.R"))
```
```{r}
# tmp <- tar_read(cleaned_df_missforest_2015_1) |> as_tibble()
# tar_read(new_data_2015_1) |> as_tibble()
# tar_read(imputed_new_data_2015_1)$ximp |> as_tibble()
# tar_read(imputed_df_2015_1) |> as_tibble()
library(tictoc)
tic()
tmp <- withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(combined_imputed_k_mapped))
toc()


tmp2 <- tmp |>
  filter(is.na(k_new_with_na)) |>
  head(1000)

tmp2 |> pull(k_imp) |> length()
tmp2 |> pull(k_new_without_na) |> length()

fit <- lm(k_imp ~ k_new_without_na, data = tmp2)
cor.test(tmp$k_imp, tmp$k_new_without_na)

fit <- lm(k_imp ~ k_ori, data = tmp2)
summary(fit)

```

```{r, eval=TRUE}
tic()
# ggplot(tmp2, aes(x = k_new_without_na, y = k_imp)) +
ggplot(tmp2, aes(x = k_ori, y = k_imp)) +
  geom_point(alpha = 0.1) +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(x = "Original", y = "Imputed")
toc()
```


```{r}
library(viridis)

tic()
tmp2 |>
  ggplot(aes(x = k_ori, y = k_imp)) +
        geom_bin2d(bins = 70) +
        scale_fill_viridis(option = "inferno", direction = -1) +
        theme_minimal()
toc()
```
