---
title: ""
author: "Masatoshi Katabuchi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
format:
  html:
    theme: coderpro
    toc: true
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
    standalone: true
    embed-resources: true
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold",
  root.dir = rprojroot::find_root('_targets.R')
)
```

```{r}
library(tidyverse)
library(targets)
library(lme4)
library(MuMIn)
library(here)
```


```{r}
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_load(fd_k_traits_csv))
d <- read_csv(here(fd_k_traits_csv))
```

```{r}
nd <- d |>
  group_by(species) |>
  nest() |>
  mutate(fit1 = map(data, ~lm(log(fd) ~ log(k), data = .x))) |>
  mutate(fit2 = map(data, ~lme4::lmer(log(fd) ~ log(k) + (1 + log(k) | sample_id), data = .x))) |>
  mutate(aic1 = map_dbl(fit1, AICc)) |>
  mutate(aic2 = map_dbl(fit2, AICc))

m1_aicc <- nd |>
  pull(aic1) |> sum()
m2_aicc <- nd |>
  pull(aic2) |> sum()
```

```{r}
fit3 <- lme4::lmer(log(fd) ~ log(k) + (1 + log(k) | xylem_type/species), data = d)
fit4 <- lme4::lmer(log(fd) ~ log(k) + (1 + log(k) | xylem_type/species/sample_id), data = d)
fit5 <- lme4::lmer(log(fd) ~ log(k) + (1 + log(k) | species/sample_id), data = d)

m3_aicc <- AICc(fit3)
m4_aicc <- AICc(fit4)
m5_aicc <- AICc(fit5)
```
```{r}
aic_df <- tibble(
  model = c("Model 1", "Moedl 2", "Model 3", "Model 4", "Model 5"),
   aicc = c(
    m1_aicc,
    m2_aicc,
    m3_aicc,
    m4_aicc,
    m5_aicc))
```
