---
title: "report"
author: "Masatoshi Katabuchi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
# link-citations: yes
# csl: templates/ecology-letters.csl
# bibliography: templates/seedling.bib
format:
  html:
    theme: spacelab #readable #sandstone #spacelab #flatly
    toc: true
    toc-depth: 2
    toc-title: Contents
    self-contained: true
    smooth-scroll: true
    highlight-style: github
  pdf:
    toc: true
    keep-tex: true
    pdf-engine: pdflatex
    highlight-style: github
    include-in-header:
      text: |
        \usepackage{xr}
        \usepackage[default]{sourcesanspro}
        \usepackage{sourcecodepro}
        \usepackage{fancyhdr}
        \usepackage{fvextra}
        \pagestyle{fancy}
        \fancypagestyle{plain}{\pagestyle{fancy}}
        \renewcommand{\headrulewidth}{0pt}
        \fancyhead[RE,RO]{Song \textit{et al}. --Ecology Letters-- Appendix SX}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  docx:
    toc: true
    number-sections: false
    highlight-style: github
    html-math-method: katex
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)
```

```{r,include=FALSE}
library(tidyverse)
library(tarchetypes)
library(here)
library(kableExtra)
library(targets)
library(loo)
source(here("R", "stan.R"))
```


```{r}
tar_load(ks_trees_csv)
d <- read_csv(ks_trees_csv)

d |>
  filter(species == "HH") |>
  filter(pressure == 0.02) |>
  filter(pres_type == "pres")

d |>
  filter(species == "HH") |>
  mutate(pres_fct = as.factor(pressure)) |>
ggplot(aes(y = ks, x = pres_type, fill = pres_fct)) +
  geom_violin() +
  geom_point(position = position_dodge(width = 0.90)) +
  facet_grid(pres_fct ~species)# +
  # scale_y_log10()
```

```{r}
targets::tar_load(anova_mvn_data)
anova_mvn_data

hist(anova_mvn_data$y)


targets::tar_load(fit4_summary_anova_mvn)
fit4_summary_anova_mvn

fit4_summary_anova_mvn |>
  filter(str_detect(variable, "diff"))
```

```{r}
targets::tar_load(fit_mvn_summary_anova_mvn)
targets::tar_load(fit_lmvn_summary_anova_mvn)
targets::tar_load(fit_gmvn_summary_anova_mvn)

fit_mvn_summary_anova_mvn |>
  filter(str_detect(variable, "diff"))

fit_lmvn_summary_anova_mvn |>
  filter(str_detect(variable, "alpha"))

fit_lmvn_summary_anova_mvn |>
  filter(str_detect(variable, "delta"))

fit_lmvn_summary_anova_mvn |>
  filter(str_detect(variable, "tau"))


fit_gmvn_summary_anova_mvn |>
  filter(str_detect(variable, "diff"))
```

```{r}
targets::tar_load(fit_mvn_draws_anova_mvn)
targets::tar_load(fit_lmvn_draws_anova_mvn)
targets::tar_load(fit_gmvn_draws_anova_mvn)

mvn_draws <- create_stan_tab(fit_mvn_draws_anova_mvn)
lmvn_draws <- create_stan_tab(fit_lmvn_draws_anova_mvn)
gmvn_draws <- create_stan_tab(fit_gmvn_draws_anova_mvn)

mvn_draws |>
  filter(q2_5 * q97_5 > 0) |>
  filter(str_detect(para, "diff"))
lmvn_draws |>
  filter(q2_5 * q97_5 > 0) |>
  filter(str_detect(para, "diff"))
gmvn_draws |>
  filter(q2_5 * q97_5 > 0) |>
  filter(str_detect(para, "diff"))
```

```{r}
targets::tar_load(fit_lmvn_simple_summary_anova_mvn_simple)
fit_lmvn_simple_summary_anova_mvn_simple
```

```{r}
targets::tar_load(dummy_data)

dummy_data$data |>
  mutate(species = as.factor(species)) |>
  mutate(pressure = as.factor(pressure)) |>
  ggplot(aes(y = y, x = pressure, col = pressure)) +
  geom_violin() +
  geom_point(position = position_dodge(width = 0.90)) +
  facet_wrap(~ species)

dummy_data$data |>
  mutate(species = as.factor(species)) |>
  mutate(pressure = as.factor(pressure)) |>
  ggplot(aes(y = y, x = species, col = pressure)) +
  geom_violin() +
  geom_point(position = position_dodge(width = 0.90)) +
  facet_wrap(~ pressure)

```

```{r}
# targets::tar_load(fit00_summary_test)
# fit00_summary_test |>
#   #head(20)
#   filter(str_detect(variable, "beta|gamma|mu"))
targets::tar_load(fit0_summary_anova)
fit0_summary_anova |>
  filter(str_detect(variable, "beta|gamma|mu"))

library(bayesplot)

targets::tar_load(fit0_draws_anova)
targets::tar_load(dummy_data)
dummy_data

mcmc_intervals(
  fit0_draws_anova,
#  pars = c("mu_hat"),
  prob = 0.8,
  regex_pars = "alpha\\[[1-5]\\]|beta\\[[1-9]\\]")
  #regex_pars = "alpha\\[[1-5]\\]")

```

# GLM

```{r}
d <- dummy_data$data

fit <- glm(y ~ as.factor(species) * as.factor(pressure), data = d)

```

```{r}

```


```{r}
targets::tar_load(fit_mvn_simple_draws_anova_mvn_simple)
targets::tar_load(fit_lmvn_simple_draws_anova_mvn_simple)
targets::tar_load(fit_gmvn_simple_draws_anova_mvn_simple)

mvn_draws <- create_stan_tab(fit_mvn_simple_draws_anova_mvn_simple)
lmvn_draws <- create_stan_tab(fit_lmvn_simple_draws_anova_mvn_simple)
gmvn_draws <- create_stan_tab(fit_gmvn_simple_draws_anova_mvn_simple)

mvn_draws |>
  filter(q2_5 * q97_5 > 0) |>
  filter(str_detect(para, "diff"))
lmvn_draws |>
  filter(q2_5 * q97_5 > 0) |>
  filter(str_detect(para, "diff"))
gmvn_draws |>
  filter(q2_5 * q97_5 > 0) |>
  filter(str_detect(para, "diff"))
```

```{r}
tar_load(dummy_data)
tar_load(fit0_draws_anova)
tar_load(fit0_summary_anova)

fit0_summary_anova

dummy_data
draws <- create_stan_tab(fit0_draws_anova)


draws |>
 filter(str_detect(para, "beta"))

draws |>
 filter(q2_5 * q97_5 > 0) #|>
  # filter(str_detect(para, "a"))
```

```{r,include=FALSE}
d <- read_csv(here("data-raw", "ks_pres_tens_five_spp.csv"))
# hist(d$pres_calib)
```


Non-log scale compares if the difference between flow rate by pressure and flow rate under tension (flow rate by pressure - flow rate under tension) is different from zero, whereas log scale compares the ratio between the two (log[flow rate by pressure / flow rate under tension]) is different from log one (log(1) = 0).

Fig. 1A (non-long)

```{r}
targets::tar_read(sma_scatter_plot)
```

```{r, include=FALSE}
targets::tar_read(sma_scatter_ks_plot)
```

Fig. 1A (log)

```{r}
targets::tar_read(sma_scatter_log_plot)
```

```{r, include=FALSE}
targets::tar_read(sma_scatter_ks_log_plot)
```

Fig. 1B-F (non-log)

```{r, fig.width = 2, fig.height = 6}
targets::tar_read(ks_bar_plot)
```


Fig. 1B-F (log)

```{r, fig.width = 2, fig.height = 6}
targets::tar_read(ks_log_bar_plot)
```

```{r,}
#knitr::knit_exit()
targets::tar_load(dummy_data)
# dummy_data

targets::tar_load(fit0_draws_anova)
pred0_draws <- create_stan_tab(fit0_draws_anova)
pred0_draws
```

```{r, fig.width = 3.5, fig.height = 3.5}
targets::tar_load(anova_data)
targets::tar_load(anova_data_log)

# d <- read_csv(here("data-raw", "pres_tens_five_spp.csv"))

d2 <- d |>
  mutate(jk = paste(d$species, d$pressure, sep = "_")) |>
  mutate(jk_fct = as.factor(jk) |> as.numeric()) |>
  dplyr::select(jk, jk_fct) |>
  unique() |>
  arrange(jk_fct)

sp_lab <- as.factor(d$species) |> levels()
pres_lab <- as.factor(d$pressure) |> levels()
int_lab <- as.factor(d2$jk) |> levels()

para_name <- c(sp_lab, pres_lab, rep(int_lab, 3), "mu")
```

```{r}
targets::tar_load(fit0_summary_anova)
targets::tar_load(fit1_summary_anova)
targets::tar_load(fit2_summary_anova)
targets::tar_load(fit3_summary_anova_gamma)
#knitr::knit_exit()

```



```{r}
fit0_summary_anova |> filter(str_detect(variable, "tau|sigma|mu"))
fit1_summary_anova |> filter(str_detect(variable, "tau|sigma|mu"))
fit2_summary_anova
fit3_summary_anova_gamma
```

```{r}
targets::tar_load(loo_)

loo_compare(loo_[[1]], loo_[[2]],loo_[[3]])
```

```{r, fig.width = 3.5, fig.height = 3.5}
# tar_load(anova_mvn_data)

d <- read_csv(here("data", "ks_pres_tens_trees.csv"))

d2 <- d |>
  mutate(jk = paste(d$species, d$pressure, sep = "_")) |>
  mutate(jk_fct = as.factor(jk) |> as.numeric()) |>
  dplyr::select(jk, jk_fct) |>
  # unique() |>
  arrange(jk_fct)

sp_lab <- as.factor(d$species)# |> levels()
pres_lab <- as.factor(d$pressure)# |> levels()
int_lab <- as.factor(d2$jk) #|> levels()

para_name <- c(sp_lab, pres_lab, rep(int_lab, 3), "mu")

pred1_draws |>
  filter(!str_detect(para, "raw"))  |>
  pull(para)

```


```{r}
targets::tar_load(fit_lmvn_draws_anova_mvn)
pred1_draws <- create_stan_tab(fit_lmvn_draws_anova_mvn)
pred1_draws[, 2:6] <- round(pred1_draws[, 2:6], digits = 3)
pred1_draws |>
  filter(!str_detect(para, "raw")) |>
  # mutate(para_name) |>
  # mutate(para_name = cell_spec(para_name, bold= ifelse(q2_5 * q97_5 > 0, TRUE, FALSE))) |>
  kbl(booktabs = TRUE, escape = FALSE, format = "html", longtable = TRUE) |>
  kable_styling()
```

```{r,eval=FALSE}
targets::tar_load(fit1_draws_anova)
pred1_draws <- create_stan_tab(fit1_draws_anova)
pred1_draws[, 2:6] <- round(pred1_draws[, 2:6], digits = 3)
pred1_draws |>
  filter(!str_detect(para, "raw")) |>
  mutate(para_name) |>
  mutate(para_name = cell_spec(para_name, bold= ifelse(q2_5 * q97_5 > 0, TRUE, FALSE))) |>
  kbl(booktabs = TRUE, escape = FALSE, format = "html", longtable = TRUE) |>
  kable_styling()

targets::tar_load(fit2_draws_anova)
pred2_draws <- create_stan_tab(fit2_draws_anova)
pred2_draws[, 2:6] <- round(pred2_draws[, 2:6], digits = 3)
pred2_draws |>
  filter(!str_detect(para, "raw")) |>
  mutate(para_name) |>
  mutate(para_name = cell_spec(para_name, bold= ifelse(q2_5 * q97_5 > 0, TRUE, FALSE))) |>
  kbl(booktabs = TRUE, escape = FALSE, format = "html", longtable = TRUE) |>
  kable_styling()


targets::tar_load(fit3_draws_anova_gamma)
pred3_draws <- create_stan_tab(fit3_draws_anova_gamma)
pred3_draws[, 2:6] <- round(pred3_draws[, 2:6], digits = 3)
pred3_draws |>
  filter(!str_detect(para, "raw")) |>
  mutate(para_name) |>
  mutate(para_name = cell_spec(para_name, bold= ifelse(q2_5 * q97_5 > 0, TRUE, FALSE))) |>
  kbl(booktabs = TRUE, escape = FALSE, format = "html", longtable = TRUE) |>
  kable_styling()
```

```{r}
pred1_draws <- create_stan_tab(fit1_draws_anova)
```

```{r}
targets::tar_visnetwork()
```


```{r}
devtools::session_info()
```

